### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by judgej** [MohammadWaleed/keycloak-admin-client#29]
We would like to use this package with Laravel 8, and that uses Guzzle 7 by default. L8 *can* use Guzzle 6, but Guzzle 7 is the new norm for Laravel and so other packages will be using it.

So, would this client be compatible with Guzzle 7, or does it use features of Guzzle 6 that have changed in Guzzle 7?

We can run some experiments ourselves, but I'm raising this here in case there are any insights direct from the source :-)

**Comment by judgej** [comment]
Ideally this package would not rely on a specific version of a specific HTTP client, but instead use an implementation of a common interface such as [php-http/client-implementation](https://packagist.org/providers/php-http/client-implementation) or (I think more accurately) [psr/http-client-implementation](https://packagist.org/providers/psr/http-client-implementation), along with your favourite client discovery package to find the implementation. That's just an idea for the future rather than a fix for the immediate issue.

**Comment by MohammadWaleed** [comment]
Hello @judgej  

Yes it should be compatible with Guzzle 7 the reason i didn't update it to Guzzle 7 was guzzle services which depends on Guzzle didn't have the support for Guzzle 7 until recently,  i have free time in the weekend for this project so i'll work on adding and checking the support for Guzzle 7 if everything was ok it'll be out by sunday.

As for your suggestion i think it'll be a great thing to have, sadly currently i don't have the knowledge to make it 
as for now i'll add it as an issue and when i have the time i'll work on it maybe for v2 of the client.

Also any support is welcome by a pull request or an issue is welcome and thank you.

**Comment by judgej** [comment]
Awesome. I've been converting a number of our internal APIs to be able to use Guzzle 6 or 7 today, and they have all worked without any code changes. We just use `"^6.0|^7.0"` now as the dependendency, it uses whichever is available. We are using mostly the PSR-7 methods, and those are pretty much fixed across Guzzle versions, so that is likely why it just works, so YMMV.

I'm going to be changing our API generator scripts to use psr/http-client-implementation at some point, so should be able to offer some prectical help after getting that sorted. No timeline for that though, as - with all things - so much to do and so little time. But I'll do what I can. We try to generate clients from OpenAPI descriptions, so we don't directly maintain all the endpoint and model code, but I have not yet been able to find an OpenAPI description for Keycloak. Doing so would change the game completely.

**Comment by judgej** [comment]
Actually, I [only just found this](https://github.com/ccouzens/keycloak-openapi/blob/master/keycloak/11.0.json) which is what you presumably use to generate your data. It's riddled with errors (over 1550), but looks like something we could play with.

**Comment by MohammadWaleed** [comment]
That's really great, as for the versions i intended to do just as you did to keep support for legacy systems.
creating OpenAPI specs would be great and give more flexibilty for the programming language used, you can help anytime you want no pressure at the end of the day this is an open source project.

**Comment by MohammadWaleed** [comment]
Closing this issue as the support added in this pull request #30 along with support for additional APIs
