### ISSUE TITLE
support addGlobalRolesToUser

### ISSUE THREAD

**Issue by bdpfreizeiten** [MohammadWaleed/keycloak-admin-client#32]
Hey,
it would be cool if you can also support addGlobalRolesToUser.

I play around and finde out that this is working, but I have no idea how to change your configuration for addGlobalRolesToUser. Tested with Keycloak 8.

`$response = (new \GuzzleHttp\Client())->request(
	'POST',
	self::BASEURL .'auth/admin/realms/{realm}/users/{user}role-mappings/realm',
	[
		'headers' => [
			'Content-Type' => 'application/json',
			'Authorization' => 'Bearer ' .$this->fetchAccessToken(),
		],
		'body' => '[
			{"id" : "7686468f-1658-4eca-ac46-390df22ba881",
			"name": "seminarleiterin",
			"composite": false,
			"clientRole": false,
			"containerId": "test"}]',
	]
);`

**Comment by MohammadWaleed** [comment]
It's implemented as i said in the readme Keycloak gives an exception, well i do test on Keycloak 7 so i guess they fixed the exception in version 8, but it is implemented and you can use it
