### ISSUE TITLE
Add impersonation and send an email-verification methods

### ISSUE THREAD

**Issue by cristian-tone** [MohammadWaleed/keycloak-admin-client#48]
It would be helpful if these 2 requests were implemented. Any plans on doing that?

**Comment by MohammadWaleed** [comment]
@cristian-tone  yes, it is planned, but lately i didn't have much time on this project, you're more than welcome to open a pull request impleminting the requests

**Comment by dsbe-ak** [comment]
It's working great for dev-develop! Any plans to release a proper version tag?

Thanks!

**Comment by MohammadWaleed** [comment]
@cristian-tone  and @dsbe-ak  the feature is released now https://github.com/MohammadWaleed/keycloak-admin-client/releases/tag/v0.25.0 , sorry for being late

**Comment by dsbe-ak** [comment]
Thank you!
