### ISSUE TITLE
getUsers returns `Array ( [error] => unknown_error )`

### ISSUE THREAD

**Issue by killua-eu** [MohammadWaleed/keycloak-admin-client#49]
Hi, I just tested this library against keycloak 12.04 with the simple

```
$client = \Keycloak\Admin\KeycloakClient::factory([
    'realm'=>'realm',
    'username'=>'user',
    'password'=>'xxxxxxxx',
    'client_id'=>'admin-cli',
    'baseUri'=>'https://id.server.com'
    ]);
print_r($client->getUsers());
```

the `print_r` returns `Array ( [error] => unknown_error )`. Any idea what emits this error?

**Comment by MohammadWaleed** [comment]
Hi, the error is recieved from keycloak itself, keycloak logs might help you determine the issue, i won't be able to look into it before the weekend,  is your keycloak installation fresh ? so i can replicate the issue

**Comment by killua-eu** [comment]
Hey @MohammadWaleed , sorry for the late reply. Yes, its a fresh install, version 12.04.

**Comment by killua-eu** [comment]
My guess is, that we both have a different configuration of the admin-cli client. By tweaking things here and there, I managed to get a 403 unauthorized error. For credentials, i'm using client id and secret. Your example provides username and password.

**Comment by killua-eu** [comment]
I managed to progress further! I switched back to the 'master' domain and things work. I do continue to have a problem with viewing other realms getting an `Unauthorized` response: {"error":"invalid_grant","error_description":"Invalid user credentials"}` error. When I set up a new realm, the default settings for the admin-cli client don't seem to do the trick. Do you per chance have an idea what needs to be set up to get things up and running? Thanks lots

**Comment by MohammadWaleed** [comment]
> I managed to progress further! I switched back to the 'master' domain and things work. I do continue to have a problem with viewing other realms getting an `Unauthorized` response: {"error":"invalid_grant","error_description":"Invalid user credentials"}` error. When I set up a new realm, the default settings for the admin-cli client don't seem to do the trick. Do you per chance have an idea what needs to be set up to get things up and running? Thanks lots

@killua-eu 

When you try to use another realm, make sure of the following 
* you set the realm name correctly in the keycloak client
* admin-cli client exists inthe new realm
* you're using keycloak client with a user that exists in the realm and have the correct role/premissions

realm users are not shared between realms, every realm is fully separated than the other,
also currently the client only supports admin-cli, but i'm planning on adding an option to pass the client name when creating new client

**Comment by killua-eu** [comment]
Hey @MohammadWaleed , thanks lots! When using a user/pass in the realm and access type public, I got things working 👍🏻  Thanks lots for the explanation, I see keycloak has a somewhat steep learning curve. 

- Is there a way to set up a user who'd have access to all realms?
- I also tried to change from the public access type to confidential and use the client_secret, but this fails with a guzzle exception  `There was an error executing the getUsers command: Undefined index: username` - is using a client_secret instead of a username and pass supported?

**Comment by MohammadWaleed** [comment]
Hi @killua-eu  you're more than welcome

* No it's not supported , check [here](https://stackoverflow.com/questions/47121643/keycloak-is-it-possible-share-a-common-set-of-users-between-realms)
* Sadly it's not supported yet, but it would be a nice addition, i was also thinking for the client to accept a token 
i'll keep the issue open and will close it once the feature is added

**Comment by MohammadWaleed** [comment]
closed as feature for using `client_secret` is added in pull request  https://github.com/MohammadWaleed/keycloak-admin-client/pull/53

and added in release version 0.23.0

**Comment by romantaranenko** [comment]
For future generations, it can be that you getting unknown error because you want to access other realm users using master realm admin token, then you need to switch realm name before calling getUsers:

```
        $credentials = array_merge(
            [
                'grant_type' => 'password',
                'client_id' => 'admin-cli',
                'baseUri' => '...',
                'username' => '...',
                'password' => '...'
             ],
        );

        $client = KeycloakClient::factory($credentials);
        $client->setRealmName(OTHER_REALM_NAME_HERE); // switch realm
        $users = $realm->getUsers();
```
