### ISSUE TITLE
Get user attributes

### ISSUE THREAD

**Issue by mchanchaf** [MohammadWaleed/keycloak-admin-client#52]
Hi, is there any way to fetch user attributes ?

![image](https://user-images.githubusercontent.com/10596721/118668544-819e6500-b7e4-11eb-9832-cb19e2678317.png)

**Comment by MohammadWaleed** [comment]
Hello, Yes you can 

after you add the attribute to the user,
 you need to create a new mapping in your client

Go to your client > Mappers > create
* Fill the name whatever you want
* Choose "User Attribute" on the Mapper type
* Set "User Attribute" as the same one you want 
* set "Token Claim Name" as the name you want the attribute to have in the JSON
* set "Claim JSON Type" as the attribute type
* save

now you should have attribute you want in the token and in the getUser api call

**Comment by mchanchaf** [comment]
Hi @MohammadWaleed thank you for response this was really helpful
