### ISSUE TITLE
getUsers call with giving username as parameter returns too much results

### ISSUE THREAD

**Issue by realGo4IT** [MohammadWaleed/keycloak-admin-client#76]
when using the getUsers() method by giving an username, e.g.
`$data = $client->getUsers(array('username'=>'myuser'));`
i get too many results because the username is not matched exactly, but more like a search-term.
For this the official API suggests to use "exact=true" in the parameter-list, like:
`$data = $client->getUsers(array('username'=>'myuser','exact'=>true));`
but this does not seem to work. I also got more than one result if "myuser" matches many in Keycloak.

**Comment by igittigitt** [comment]
Great! Thank you so much :-)
