### ISSUE TITLE
Remove auth/ in base URL

### ISSUE THREAD

**Issue by funkycram** [MohammadWaleed/keycloak-admin-client#84]
Keycloak used to have `auth/` by default and it couldn’t be removed.

Fortunately, the current version of Keycloak (v 17.0 and newer) does not have it by default.

Since all the future versions of Keycloak would run on the base “/“ instead of `auth/`, we should not add `auth/` in the code.

**Comment by funkycram** [comment]
See PR https://github.com/MohammadWaleed/keycloak-admin-client/pull/85

**Comment by MohammadWaleed** [comment]
Thank you for the pull request, but i think instead of removing it entirely, we should check or add an option that tells the keycloak version so we can decide whether we keep `auth` or remove it from the url, to keep backwards compatibility with older keycloak versions

**Comment by funkycram** [comment]
I'm not sure we need backwards compatibility if you specify that version 0.30 changes the URL.
Because you can still use this version with old Keycloak version if you add /auth at the end of the `baseUri`.
E.g: `'baseUri' => 'http://127.0.0.1:8180/auth',`
If think adding an option will add complexity and confusion as it is possible on Keycloak 17 to define this base. Default is without `auth/`, but you can decide adding it or adding another name, e.g. `my-custom-base/`

**Comment by MohammadWaleed** [comment]
hmmm i guess you're right, i have an idea, can you please update the `README.md` file and add that this version support Keycloak 17+ and for older versions use the package version [v0.29.0](https://github.com/MohammadWaleed/keycloak-admin-client/releases/tag/v0.29.0) or less

**Comment by funkycram** [comment]
Done: https://github.com/MohammadWaleed/keycloak-admin-client/pull/85/files
I formulated this specificity a little differently, you will tell me if that suits you.

**Comment by MohammadWaleed** [comment]
That's perfect thank you
